### ISSUE TITLE
Error changing representative

### ISSUE THREAD

**Issue by regfaker** [appditto/natrium_wallet_flutter#102]
Hi, I'm getting `An error occured. Try again later.` (same as in https://github.com/appditto/natrium_wallet_flutter/issues/78) when trying to change representative to nano_3xeqndf4bsgfs1yj43mx4a8okycj8a63mfqtcc4wigm5a38ftoywhoax4d37
I've tried to change to other representatives and it was successful, so it can be something related to this particular representative but I don't know what - it would be good to enhance the error message with cause. I've also tried other wallet (exodus) and there I can change to this representative without problem.
Natrium v2.3.4
Thanks for your wallet anyway

**Comment by regfaker** [comment]
FYI that account and its wallet was destroyed today. I had created new wallet and its account `nano_3cxj9z11z1um61m51paiff4pw5fdttzmpojbwcr1hqbduwi4rqtjws7cxdc8` but this also cannot be used as representative (same error). Why?

**Comment by bbedward** [comment]
Fixed by 781a1b6cd7540afd150c57d1a9798087c1d68789
