### ISSUE TITLE
Implementing a performance chart

### ISSUE THREAD

**Issue by Hebrasco** [appditto/natrium_wallet_flutter#106]
Hello,

I'm currently implementing a chart that show the current and past value of your wallet.
At this moment, I'm trying to get real values.

It seems like we only get the current price pushed periodicly with an event.
Do you guys know and recomment a platform where I can get the price history from?

**Comment by Hebrasco** [comment]
What about the coinGecko api?
https://www.coingecko.com/en/api

**Comment by bbedward** [comment]
We use the coingecko API to push the current price of the wallet, historical values are out-of-scope and not something we're interested in implementing.
