### ISSUE TITLE
Wallet Not Loading

### ISSUE THREAD

**Issue by NanoRebel** [appditto/natrium_wallet_flutter#107]
I’ve been trying to log into my Natrium wallet for almost an hour. After logging in it just blinks like it’s loading but never does. Any suggestions would be greatly appreciated. Thanks.

**Comment by bbedward** [comment]
The servers will be down for at least 2 more hours, we're moving the ledger to a different volume and it's taking longer than anticipated.

**Comment by NanoRebel** [comment]
Thanks.
