### ISSUE TITLE
Why natrium sends nano without my permission?

### ISSUE THREAD

**Issue by fairking** [appditto/natrium_wallet_flutter#111]
Why natrium sends nano without my permission?

**Comment by bbedward** [comment]
The app doesn't have the capability of doing that unless you compromised your seed

**Comment by fairking** [comment]
And why are you not on f-droid?

**Comment by fairking** [comment]
So does it mean I must change my wallet address? Just wondering what do I need to do.
Appreciate any help guys.

**Comment by bbedward** [comment]
I don't understand the question, your address is derived from your seed. You can change it by creating a new wallet or importing a different seed and you can create multiple accounts in the natrium settings

**Comment by fairking** [comment]
> @bbedward I don't understand the question

I found that transaction in my wallet.

![Screenshot_20210210-135846](https://user-images.githubusercontent.com/13495631/107519539-4cacc180-6ba8-11eb-957f-58e7195bc833.png)

**Comment by bbedward** [comment]
This is from changing your natricon, also the app does get your permission to send ~0.001235 Nano.

It shows you a send confirmation screen, and requires biometric authentication or PIN authentication, just like it would any other time you send Nano. Also the Nano gets refunded automatically as you can see, it is just used as an identifier to choose your natricon.

**Comment by fairking** [comment]
Ok. Thanks @bbedward . 
Now I understand what it was. I thought my wallet was compromised.
