### ISSUE TITLE
Adding to "enum OverlayTheme" in barcode_scan.dart

### ISSUE THREAD

**Issue by tlietz** [appditto/natrium_wallet_flutter#143]
I want to try and make a custom theme for Natrium. However, this requires changing the OverlayTheme enum in barcode_scan.dart, which is not in the natrium_wallet_flutter github directory. Is there something I am missing to make a custom theme?

**Comment by bbedward** [comment]
It is in this repo: https://github.com/bbedward/flutter_barcode_reader , the barcode scanner is a separate plugin and is a native view so needs to be themed in android/iOS separately. You'll find all the references there.
