### ISSUE TITLE
Amount in deep link not working

### ISSUE THREAD

**Issue by Javdu10** [appditto/natrium_wallet_flutter#15]
Using this link : xrb:xrb_1natrium1o3z5519ifou7xii8crpxpk8y65qmkih8e8bpsjri651oza8imdd?amount=1

Or

xrb:nano_1natrium1o3z5519ifou7xii8crpxpk8y65qmkih8e8bpsjri651oza8imdd?amount=1

It doesn’t fill the amount

On IOS

Have a great day 😇

**Comment by bbedward** [comment]
The minimum amount to send is 0.000001 Nano and the amount in the URI is intended to be in raw.

So if you intended to send 1 NANO it would be 1000000000000000000000000000000

Unit converter is here to help with it: https://nanoo.tools/unit-converter

**Comment by Javdu10** [comment]
Hmm, nanowallet doesn’t consider it as raw but as NANO, that’s why the link didn’t worked gotcha

**Comment by bbedward** [comment]
The standard specifies it should always be in raw: https://github.com/nanocurrency/nano-node/wiki/URI-and-QR-Code-Standard
