### ISSUE TITLE
Slovenian translation updates #2

### ISSUE THREAD

**Issue by Perza83** [appditto/natrium_wallet_flutter#16]
After thorough usage I would like to correct some minor issues of some translated words/sentences for better understanding and consistency.

Change of the word "Malo" to "nekaj":

 "exampleCardLittle": "nekaj",
  "@exampleCardLittle": {
    "description": "example_card_little",
    "type": "text",
    "placeholders": {}

Change of the word "Veliko" to "več":

 "exampleCardLot": "več",
  "@exampleCardLot": {
    "description": "example_card_lot",
    "type": "text",
    "placeholders": {}

Change of the word "Vnesi" to "Vnesite":

"pinEnterTitle": "Vnesite PIN",
  "@pinEnterTitle": {
    "description": "pin_enter_title",
    "type": "text",
    "placeholders": {}

Change of the word "Vnesi" to "Vnesite":

"unlockPin": "Vnesite PIN za odklep Kalium",
  "@unlockPin": {
    "description": "unlock_kalium_pin",
    "type": "text",
    "placeholders": {}

Change of the word "Vnesi" to "Vnesite":

 "pinSeedBackup": "Vnesite PIN za shranitev ključa",
  "@pinSeedBackup": {
    "description": "settings_pin_title",
    "type": "text",
    "placeholders": {}

Change of the word "papirne" to "papirnate" and "Pritisni" to "Pritisnite":

  "transferIntro": "Postopek bo prenesel znesek iz papirnate denarnice v vašo Kalium denarnico.\n\nPritisnite \"%1\" gumb za začetek.",

Thank you very much!

**Comment by bbedward** [comment]
Thanks, done in 1281fdba083cae180c88a7f472849e2002a1cc45
