### ISSUE TITLE
Problem send receive unconfirmed

### ISSUE THREAD

**Issue by gchalitam** [appditto/natrium_wallet_flutter#169]
i have a problem since 3 days ago when 2miners send me the pay of the mining day and natrium don't show me the new balance, now i try to send my full balance to the exchange but nothing happen, so i just see send and unconfirmed

![IMG_1644](https://user-images.githubusercontent.com/105876359/169350688-97832700-f54f-4599-bc6d-fb78eaffba11.PNG)
d

**Comment by helmyhabsyi** [comment]
Any solution dude? Same here

**Comment by gchalitam** [comment]
In discord natrium say is a dd2 attack and then try to solve i hope can fix the most fast posible

**Comment by bbedward** [comment]
We've upgraded our nodes to V23.1 which should resolve the issues, but it may take some time for everything to sync up.
