### ISSUE TITLE
Use/Create nano_ prefix account

### ISSUE THREAD

**Issue by kvrban** [appditto/natrium_wallet_flutter#17]
Hi, i just installed latest Beta from Google Play. The Nano address which was created still use xrb_ Prefix. Should be nano_

**Comment by bbedward** [comment]
Hi, the prefix is only cosmetic. Either xrb_ or nano_ will work.

We went back to using xrb_ because a lot of the nano ecosystem doesn't work well with nano_ yet

When that changes we'll eventually make it all display as nano_ again
