### ISSUE TITLE
Natrium not showing the block explorer

### ISSUE THREAD

**Issue by fairking** [appditto/natrium_wallet_flutter#180]
Hi, does anyone know why Natrium not showing the block explorer? There is just an empty white page.

![image](https://user-images.githubusercontent.com/13495631/216756043-ee737c49-db40-47ff-88f3-d016af7b69d4.png)

![image](https://user-images.githubusercontent.com/13495631/216756064-e1b19a96-9539-4158-abdc-eebfd44706d8.png)

Version: v2.4.5

**Comment by cstrouse** [comment]
Looks like it's an issue with the default (nanocrawler.cc) has an issue with their SSL certificate. Do you get an SSL warning if you visit the block explorer URL in a browser directly?

**Comment by Heclalava** [comment]
Same issue here. Reported by OP in February and it's now May. How has this not been fixed yet?

**Comment by d4f5409d** [comment]
> Looks like it's an issue with the default (nanocrawler.cc) has an issue with their SSL certificate. Do you get an SSL warning if you visit the block explorer URL in a browser directly?

Nanocrawler is not @ https://nanoblockexplorer.com

**Comment by kopeboy** [comment]
Please guys fix this. You are the most popular nano wallet and even in the recent giveaway people were complaining about this ([example](https://www.reddit.com/r/CryptoCurrency/comments/1fwphyf/comment/lqge7o9/)).

There are many available explorers now:

1. https://spynano.org/
2. https://nanexplorer.com/nano
3. https://blocklattice.io/
4. https://nano.community/
5. https://nanobrowse.com/
6. ...

**Comment by kopeboy** [comment]
A definitive fix would be to let the user input the path of his preferred (& working!) explorer for checking a transaction, like `https://spynano.org/hash/` or `https://nanobrowse.com/block/`...
