### ISSUE TITLE
Deeplinking

### ISSUE THREAD

**Issue by chrisdaniells** [appditto/natrium_wallet_flutter#21]
Preface: I'm not an app developer, so if the answers can be found in the code I do apologise, and I can't find any docs or specs for this.

I see that you've set up deep linking for "nano://" and "xrb://", but I can't find the required path with which to send the recipient address. (e.g. "nano://address/xrb_28383.../quantity/100")

Also, is it possible to go back to the previous activity once a transaction is sent? E.g. a user clicks a web link in a browser, is redirected to Natirum and sends the funds, and is then redirected back to the browser?

P.S. If the OpenCAP alias protocol is enabled, it'd be great to be able to send the alias via the deep links too.

**Comment by bbedward** [comment]
Hi,

Deep links follow the URI standard Nano has, where amount is optional and in raw. https://developers.nano.org/docs/uri-qr-code-standard/

Redirecting back to previous activity is probably not something that can really be done reliably and, probably not at all on iOS.

OpenCAP is also not supported, but there's another GitHub issue for it.
