### ISSUE TITLE
Getting error from gradle when run on android

### ISSUE THREAD

**Issue by lunwhl** [appditto/natrium_wallet_flutter#23]
First of all, thanks for sharing such nice flutter project with us.

I have a problem to run this project on android. Every was fine on iOS.
The error is shown as below.

* Error running Gradle:
ProcessException: Process "/Users/mac/shopping/natrium_wallet_flutter/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mac/shopping/natrium_wallet_flutter/android/app/build.gradle' line: 65

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: /Users/mac/shopping/natrium_wallet_flutter/android/gradlew app:properties

Please review your Gradle project setup in the android/ folder.

Besides that, I still found this 'Cannot resolve symbol GradleException' in Android studio like the picture below.
<img width="843" alt="Screen Shot 2019-03-27 at 5 25 22 PM" src="https://user-images.githubusercontent.com/19488286/55064760-7abcb180-50b5-11e9-9074-f0235f69f94b.png">

Looking for help with this. thx

**Comment by bbedward** [comment]
Hi, there's two considerations on Android.

First you need to create a file called `local.properties` in the android/ folder. It should contain location to flutter SDK like so:

```
sdk.dir=/path/to/my/Android/sdk
flutter.sdk=/path/to/flutter_sdk/flutter
flutter.versionName=2.0.1
flutter.versionCode=27
flutter.buildMode=release%   
```

This might be automatically resolved for you in VS Code or Android Studio, but it may have not been able to auto-detect the android/flutter SDK.

Second is, that builds require the keystore information in android/key.properties.

I removed this dependency in a1291444db07b67c8d055b2ebdf851b54c80861d

Hopefully you can build it now

**Comment by lunwhl** [comment]
> Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
Error launching application on Android SDK built for x86.

I have this error but it seems like I cannot test with android emulator since it is a x86 architecture emulator. It is a must to deploy this project on arm?

**Comment by bbedward** [comment]
Hi, the build.gradle only specifies arm and arm64 targets because of https://github.com/flutter/flutter/issues/18494

I meant to add x86 before we release to the play store, but haven't done it yet.

I'll add x86 later today.

**Comment by bbedward** [comment]
Hi, I added x86 and x64 targets.

You can build for one of these with:

`flutter build apk --debug --target-platform=android-x86`

or

`flutter build apk --debug --target-platform=android-x64`

I'm not sure if it's possible to make production builds with an x86 or x64,  but it should work well enough for the emulator.

**Comment by lunwhl** [comment]
Thanks you for your hard work ward. I will just close the issue. Everything is working fine now.
