### ISSUE TITLE
Version solved failed

### ISSUE THREAD

**Issue by amitted** [appditto/natrium_wallet_flutter#39]
Running "flutter packages get" in natrium_wallet_flutter-master...     
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because natrium_wallet_flutter depends on json_serializable >=2.1.0 which requires SDK version >=2.1.1 <3.0.0, version solving failed.

pub get failed (1)
Process finished with exit code 1

Can you inform me which flutter channel was using I am getting the same issue over and over again I am on Stable channel of Flutter Is there any fix available for this??

**Comment by bbedward** [comment]
Current app should build on the stable channel of flutter.

Ensure you run `flutter packages upgrade` to update all of the dependencies.
