### ISSUE TITLE
Publishing the app with another ID for a closed beta test

### ISSUE THREAD

**Issue by azazel75** [appditto/natrium_wallet_flutter#40]
Hi guys, I'm modifying you nice app to add an alternative payment system to it (manta). Eventually all the code will be open sourced  and converted into a PR here but as of now I just want to publish the modified app as a "closed" beta on google play. To do that, I need to change the app's ID to something else but then the build system starts complaining about missing firebase account so I wanted to ask you a few questions:

- is possible to change the id but keep using your firebase acoount?
- is firebase really mandatory to run the app?
- i'm not an expert on the matter, what's its role? I see the "server" app but it's unclear to me what's the purpose of the firebase. is it "just" to update currency conversion rates?

More generally, what you advise me to do? I'm open to suggestions, thanks

**Comment by bbedward** [comment]
1) Creating a firebase account is free and pretty simple. I would recommend doing that, as with firebase the app is registered with the app identifier. You'll get instructions on the firebase website and can add the `google-services.json` to android/app for Android, and for iOS you can add `GoogleService-Info.plist` to the ios folder.

2) No, you can easily strip all of the firebase stuff from the app. The token is optional and doesnt need to be included in the requests to the server "fcm_token_v2" it's called.

3) Firebase is used for push notifications, in our case we are using "Firebase Messaging" which is one of the firebase products. The client gets a token, sends it to the server, and the server can send push notifications to that specific client.

**Comment by azazel75** [comment]
@bbedward thanks for your reply, in the case where I set up a firebase account, I'll have to also setup a server service, is it correct?

**Comment by bbedward** [comment]
No, you dont have to. If you dont intend to use any firebase services then I would remove it all together.

If you plan to at some point in the future, there's no harm in having the client support it now.
