### ISSUE TITLE
Option to add a short message to a payment

### ISSUE THREAD

**Issue by athloni** [appditto/natrium_wallet_flutter#44]
It would be nice if there would be an option to add a short message (reference) to an transaction (Natrium to Natrium). Like "Thanks for the nice diner". 
That way the receiver knows why he received the payment.

**Comment by bbedward** [comment]
Duplicate of #7 

We're somewhat limited on the length of messages, if we go the on-chain route, since nano doesnt have any data fields on blocks. But it's definitely achievable

**Comment by athloni** [comment]
Great man!!!!

**Comment by athloni** [comment]
But I prefer to do it OFF chain because of privacy. So Natrium to Natrium only. Other wallets cab adopt it I they wan't to.
