### ISSUE TITLE
Degraded animations in release mode compiled app

### ISSUE THREAD

**Issue by azazel75** [appditto/natrium_wallet_flutter#45]
Hi guys, I'm sorry to bother you with a problem that's not your, it just involves your app's code. After #40 I have successfully compiled the application using another application ID. What happens now is that in debug builds the animations (like the initial on the welcome screen) display as expected but when I build the app in "release mode" with `flutter build apk` the animations then seems "degraded", I don't know how to  describe it better, you can see a screenshot [here](https://files.azazel.it/index.php/s/RPSjBC5pXWBbkj2?path=%2FShots#/Shots/Screenshot_20190627-120713_Natrium.png). Do you have any clue of what the issue might be?

Thanks in advance

**Comment by bbedward** [comment]
Yes, I only noticed it on 32-bit devices, I created in issue to track it here: https://github.com/2d-inc/Flare-Flutter/issues/87

Might be worth trying flutter master channel to see if its been resolved there.
