### ISSUE TITLE
Scanning qrcode does not display amount since last update

### ISSUE THREAD

**Issue by bitrequest** [appditto/natrium_wallet_flutter#53]
I noticed that in the latest update the amount does not get displayed when scanning a qrcode.
This used to work before the last update. I guess it has something to do with the 'Support manta deep link URI scheme' update.

For example, i created a qrcode from this URI scheme:
nano:nano_33smorban34ozbgs5h6xsapdf5rm1ttu4stfdksdt8ywdnd3ynjc717fbjtg?amount=12000000000000000000000000000000

This should display the amount of 12 Nano in the 'send dialog'

![qr](https://user-images.githubusercontent.com/47079460/67523812-b3eeeb80-f6af-11e9-9add-806f6bca47bb.png)

But remains empty:

![send_dialog](https://user-images.githubusercontent.com/47079460/67524643-61aeca00-f6b1-11e9-9ce7-37abf2aef200.png)

**Comment by bbedward** [comment]
Thank you, issue is resolved - will be in an update soon.
