### ISSUE TITLE
SEND transaction created when changing representative

### ISSUE THREAD

**Issue by rafaelpac** [appditto/natrium_wallet_flutter#68]
I came to know about an issue that happens when somebody tries to change the representative.
Apparently, a SEND transaction was created and took away some Nanos to a burn address.
More details here: https://www.reddit.com/r/nanocurrency/comments/f6e057/bug_in_the_natrium_wallet_help_me/

**Comment by bbedward** [comment]
Fixes in https://github.com/appditto/natrium_wallet_flutter/commit/f538730db4fd2db8618bab448c5c13e79ccd35d0
