### ISSUE TITLE
[Question] Design Patterns in Natrium

### ISSUE THREAD

**Issue by santiblanco99** [appditto/natrium_wallet_flutter#80]
Hi, more than an issue I wanted to ask you guys which design patterns and styles were taken into account when designing the software architecture of the app? I like the way you guys developed the app and I wanted to know what type of good practices I could use in my own projects. Thank you in advance for the help!

Sincerely,
Santiago Blanco

**Comment by bbedward** [comment]
I recommend you also check out Blaise, which does some of the things we would do in a potential Natrium rewrite: https://github.com/appditto/blaise_wallet_flutter

Natrium was initially developed shortly after Flutter 1.0 was released, and was one of our first flutter projects. So there's some things we would do differently now than what's reflected in the codebase - just based on our experience and what we've learned.

Flutter is pretty flexible and there's many ways to do some things, this is just sort of the blue print that works for us.

1) Use [Provider](https://pub.dev/packages/provider) for global state. This would be things such as selected language, theme, etc. Changes that propagate throughout the entire app. Natrium uses an InheritedWidget for this purpose, using Provider would just remove a lot of the boilerplate code Natrium uses.

2) Use [MobX](https://pub.dev/packages/mobx) for all other state management. We like to use mobx for things that have more complex actions (e.g. for mutating the wallet state). [example](https://github.com/appditto/blaise_wallet_flutter/blob/master/lib/store/wallet/wallet.dart) Again this is just our preference for state management.

3) Use [GetIt](https://pub.dev/packages/get_it) as a service locator. We like to use GetIt for "singleton" services mainly. E.g. a websocket client that you only want to instantiate once or an HTTP client.

4) Lastly, widget everything. Make every custom component a separate widget, that's the flutter way. For example we have a custom TextField, we make our own widget for it, or our own Button, make a widget, etc.

**Comment by santiblanco99** [comment]
Noted. Thanks for taking the time to answer
