### ISSUE TITLE
NFC no longer picks up the amount

### ISSUE THREAD

**Issue by ghost** [appditto/natrium_wallet_flutter#83]
https://www.reddit.com/r/nanocurrency/comments/guqqfs/buildoff_nano_espresso_nfc_this_coffee_machine/fskg9wl?utm_source=share&utm_medium=web2x

**Comment by bbedward** [comment]
Could you provide more info? Like the URI that isn't working, can you try a larger amount to see if it's related to #82

**Comment by akutheman** [comment]
Maybe fcdeluxe on Reddit can provide more information, he made build-off submission. I just added the issue because nobody else had.

**Comment by akutheman** [comment]
Someone else added:

_Huawei p20 here. Deep links no longer work with the amount *unless Natrium has been opened first and unlocked. Then deep links successfully fill in the amount field. Natrium is used in every single video which is testament to how brilliant a wallet it is, well done :) hope you squish this bug_

**Comment by bbedward** [comment]
Unable to reproduce with deep links, which are handled exactly the same as URIs read via NFC.

Need some more info with steps on how to reproduce in order to resolve it.

**Comment by nanotaa** [comment]
I am fcdeluxe. I own a Oneplus 7t. After the last update of Natrium the amount is no longer automatically filled in. The QR code continues to work perfectly. Can I do tests to help you?

**Comment by akutheman** [comment]
Still a problem and @nanotaa has offered to help

**Comment by bbedward** [comment]
@nanotaa  you are including the scheme for the URI correct? e.g.

```nano:nano_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?amount=1000000000000000000000000000000```

If so can you try previous versions from https://github.com/appditto/natrium_wallet_flutter/releases to find the last working version.

**Comment by nanotaa** [comment]
> @nanotaa you are including the scheme for the URI correct? e.g.
> 
> `nano:nano_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?amount=1000000000000000000000000000000`
> 
> If so can you try previous versions from https://github.com/appditto/natrium_wallet_flutter/releases to find the last working version.

The URI is correct.

I have installed version 2.1.8 and it works perfectly.
Since version 2.2.1 it does not work.
If necessary, I am available for other tests.

**Comment by otonashixav** [comment]
Was Natrium open when scanning? I've found that the amount isn't picked up in general if Natrium isn't open when a URI is opened. For example clicking on a link in a browser with `nano:nano_xxx&amount=yyy` will not autofill the amount if Natrium is closed, but will autofill if Natrium is open in the background. This is of course a seperate issue.

**Comment by JerzyStanislawski** [comment]
Hello @bbedward 

I can confirm, in current version amount sometimes shows up, sometimes not when intent triggered by NFC.
I can't figure out the way to reproduce it, majority of times (like 80%) the amount doesn't show up, sometimes it does.
I am certain the format is correct and the amount is within the wallet's range.
When version downgraded to 2.1.8 - it works smoothly 100% times. 
Did you have a chance to take a look at this? Natrium is awesome and NFC is a killer feature, would be cool to fix it.

Regards

**Comment by bbedward** [comment]
6169e4172704cf5773b6a8031dcff2c1750f7d37 might somewhat solve it, I don't know how to test NFC and haven't received any guidance so reproducing things like this are hard for me.

A possible assumption is that the balance check wasn't working because balance wasnt quite yet loaded at that time or something.

**Comment by JerzyStanislawski** [comment]
I checked a couple of times on v2.4.3 and it always worked.
Thank you!
