### ISSUE TITLE
Send button swipe-up doesn't work

### ISSUE THREAD

**Issue by akutheman** [appditto/natrium_wallet_flutter#84]
It sometimes says amount too small, sometimes not entering amount at all.
Scanning QR manually works fine.
Latest Natrium version, Android.

**Comment by bbedward** [comment]
It doesn't enter amount when your balance is < amount, the amount too small bug was fixed in bc5b389

**Comment by akutheman** [comment]
This should not have been closed @bbedward , it is not fixed.

**I have plenty of balance.**

I was asked to pay 0.000079 NANO on Sendr.space

If I scan QR, all is fine.

If I swipe-up, it says minimum send amount is 0.000001

**Comment by bbedward** [comment]
It was fixed in bc5b389

**Comment by akutheman** [comment]
Ok, two different fixes. got it, thanks.

**Comment by bbedward** [comment]
Referring to the "not entering amount at all", that usually occurs when balance is less than the raw amount. The minimum send amount issue is fixed and will be in a future release (likely 2.3.1)
