### ISSUE TITLE
Changing representative fails

### ISSUE THREAD

**Issue by ghost** [appditto/natrium_wallet_flutter#87]
Hangs for a long time, then "An error occured. Try again later."

That message has a typo by the way, should be _occurred_

I'm on 2.3.2

**Comment by JohnGarnham** [comment]
This is also happening to me.

I can change my rep successfully from a list, but it never works when I try to manually enter the rep information. It fails for both scanning the QR code and for manually entering the address. It just shows an error message "An error occurred. Try again later." I have been encountering this same error for weeks now.

To troubleshoot, I changed my rep from one of the ones on the list, and it changed successfully. I took note of which rep this was and recorded its address down, and then changed it back to my old one. Then I went back to attempt to change my rep manually and manually entered the address of the rep I was just able to change to. It gave me the error "An error occurred. Try again later." Same thing for scanning its QR code.

So it seems to be not related to the node itself but in the code for changing it manually. I can change my rep to one of the ones on the list, but if I look up that rep on the list and try to manually enter it it shows me an error.

I'm using Natrium v2.4.1
