### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by rotilho** [appditto/natrium_wallet_flutter#88]
Does Natrium have any plans to implement some sort of subscription?

This is not supported in protocol level but wallets could support something like that. A service could expose a deep link for the subscription which contains the address, amount, currency (USD, EUR, NANO, etc), frequency, start date, and optionally end date.

After clicking in the link the user could trust or not the service. If the user trusts the service no more action will be required and nanos would be sent periodically without any more action from the user if the user doesn't trust the service a notification would be received and the user would need to confirm.

That would allow subscription-based services to easily accept Nano.

**Comment by mitche50** [comment]
Hey - I have made a subscription service for the Nano Build Off (https://nanorepeat.com) and will be trying to get services to implement in the future.  Hopefully Natrium will be an early adopter!
