### ISSUE TITLE
withdrawal pending

### ISSUE THREAD

**Issue by quendom** [appditto/natrium_wallet_flutter#91]
I withdraw nano from natrium to binance wallet but still not receive it. It is over 24 hours already. [Screenshot_20200816-224132.jpg](https://user-images.githubusercontent.com/69311750/90349338-13b5e900-e06c-11ea-8c8a-fa8893708609.jpg) it is still pending

**Comment by bbedward** [comment]
You need to contact binance support, Natrium made the transaction and it was confirmed by the network - it's binance's responsibility to credit your account.
