### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by Hebrasco** [appditto/natrium_wallet_flutter#99]
if I run 
```flutter packages get```
I get the following error.
```
Because natrium_wallet_flutter depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.
So, because natrium_wallet_flutter depends on intl ^0.16.0, version solving failed.
Running "flutter pub get" in natrium_wallet_flutter...                  
pub get failed (1; So, because natrium_wallet_flutter depends on intl ^0.16.0, version solving failed.)
```

I'm not able to fix this. Maybe someone else can help me?

Flutter 1.26.0-2.0.pre.103 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 32741c0ec8 (12 hours ago) • 2020-12-21 18:34:02 -0600
Engine • revision af6889a600
Tools • Dart 2.12.0 (build 2.12.0-169.0.dev)

**Comment by Hebrasco** [comment]
I fixed it by switching from the Flutter dev channel to the stable channel.

**Comment by bbedward** [comment]
You need to update the intl dependency in pubspec.yaml to ` 0.17.0-nullsafety.2` to build against dev channel.
